# Generated by Django 5.0.2 on 2024-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('Book_name', models.CharField(max_length=25)),
                ('Book_serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Author_name', models.CharField(max_length=50)),
                ('Number_of_pages', models.IntegerField()),
                ('Genre', models.CharField(max_length=40)),
                ('Year_of_book_published', models.IntegerField()),
                ('No_of_chapters', models.IntegerField()),
            ],
        ),
    ]
